[package]
name = "simple_command"
version = "0.1.2"
authors = ["Rukai <rubickent@gmail.com>"]
edition = "2018"
description = "Simple command runner for build.rs"
license = "MIT"
repository = "https://github.com/rukai/simple_command"
keywords = ["simple", "command", "runner", "build", "rs"]
